# Generated by Django 3.2.5 on 2021-10-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_userresponses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponses',
        ),
    ]
