# Generated by Django 3.2.5 on 2021-10-03 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0003_delete_userresponses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.state')),
            ],
        ),
    ]
