# Generated by Django 3.2.5 on 2021-10-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0006_userresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponses',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dropdown.city'),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dropdown.country'),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dropdown.district'),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dropdown.state'),
        ),
    ]
