# Generated by Django 3.2.5 on 2021-10-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0007_auto_20211003_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponses',
        ),
    ]
