# Generated by Django 3.2.5 on 2021-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0010_alter_userresponses_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponses',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
